/*
  BASE DE DATOS DE SigueEseHastag
*/

DROP DATABASE hastag;

CREATE DATABASE hastag;

USE hastag;



DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS HASTAG;
DROP TABLE IF EXISTS PUBLICACION;
DROP TABLE IF EXISTS TOKEN;


CREATE TABLE USUARIO (
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  NOMBRE       varchar(20) NOT NULL,
  CONTRASEÑA   varchar(100) NOT NULL,
  PRIMARY KEY  (ID)
);



CREATE TABLE HASTAG (
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  NOMBRE      varchar(20)  NOT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE PUBLICACION (
  ID MEDIUMINT NOT NULL AUTO_INCREMENT,
  NOMBRE      varchar(20)  NOT NULL,
  CONTENIDO  varchar(100) NOT NULL,
  IMAGEN    varchar(20) NOT NULL,
  FECHA  varchar(30) NOT NULL,
  PRIMARY KEY (ID)
);






