/*
  BASE DE DATOS DE SigueEseHastag
*/


USE hastag;
/* SET FOREIGN_KEY_CHECKS=0;   si es que se agregan las tablas mas de una vez */
SET FOREIGN_KEY_CHECKS=0;



DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS HASTAG;
DROP TABLE IF EXISTS PUBLICACION;
DROP TABLE IF EXISTS TOKEN;


CREATE TABLE USUARIO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE       VARCHAR(20) NOT NULL,
  CONTRASEÑA   VARCHAR(100) NOT NULL
 
);



CREATE TABLE HASTAG (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE      VARCHAR(200)  NOT NULL,
  ID_USUARIO INT,
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE

 
);


CREATE TABLE PUBLICACION (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE      VARCHAR(200)  NOT NULL,
  CONTENIDO  VARCHAR(200) NOT NULL ,
  IMAGEN    VARCHAR(20) ,
  FECHA  TIMESTAMP NOT NULL,
  ID_HASTAG INT NOT NULL,
  FOREIGN KEY (ID_HASTAG) REFERENCES HASTAG(ID) ON DELETE CASCADE

);

CREATE TABLE TOKEN (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMAIL VARCHAR(200) NOT NULL,
  TOKEN VARCHAR(200) NOT NULL
);






